using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.Diagnostics;
using DataAccessPostgreSqlProvider;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Autofac;
using SeadQueryCore;
using SeadQueryCore.QueryBuilder;
using SeadQueryTest;

namespace SeadQueryTest.Graph {

    [TestClass]
    public class GraphTests
    {

        private dynamic expectedEdges = new dynamic[] {
            new {  SourceTableName = "countries", TargetTableName = "tbl_location_types", Weight = 20},
            new {  SourceTableName = "countries", TargetTableName = "tbl_rdb", Weight = 150},
            new {  SourceTableName = "countries", TargetTableName = "tbl_rdb_systems", Weight = 150},
            new {  SourceTableName = "countries", TargetTableName = "tbl_relative_ages", Weight = 70},
            new {  SourceTableName = "countries", TargetTableName = "tbl_site_locations", Weight = 5},
            new {  SourceTableName = "countries", TargetTableName = "tbl_taxa_seasonality", Weight = 60},
            new {  SourceTableName = "countries", TargetTableName = "view_places_relations", Weight = 20},
            new {  SourceTableName = "metainformation.tbl_denormalized_measured_values", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "metainformation.view_abundance", TargetTableName = "tbl_analysis_entities", Weight = 2},
            new {  SourceTableName = "metainformation.view_abundance", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "metainformation.view_abundances_by_taxon_analysis_entity", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "metainformation.view_abundances_by_taxon_analysis_entity", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "metainformation.view_sample_group_references", TargetTableName = "tbl_biblio", Weight = 80},
            new {  SourceTableName = "metainformation.view_sample_group_references", TargetTableName = "tbl_sample_groups", Weight = 15},
            new {  SourceTableName = "metainformation.view_site_references", TargetTableName = "tbl_biblio", Weight = 80},
            new {  SourceTableName = "metainformation.view_site_references", TargetTableName = "tbl_sites", Weight = 15},
            new {  SourceTableName = "metainformation.view_taxa_biblio", TargetTableName = "tbl_biblio", Weight = 10},
            new {  SourceTableName = "metainformation.view_taxa_biblio", TargetTableName = "tbl_taxa_tree_master", Weight = 2},
            new {  SourceTableName = "tbl_abundance_elements", TargetTableName = "tbl_abundances", Weight = 20},
            new {  SourceTableName = "tbl_abundance_elements", TargetTableName = "tbl_dating_material", Weight = 20},
            new {  SourceTableName = "tbl_abundance_elements", TargetTableName = "tbl_record_types", Weight = 20},
            new {  SourceTableName = "tbl_abundance_ident_levels", TargetTableName = "tbl_abundances", Weight = 20},
            new {  SourceTableName = "tbl_abundance_ident_levels", TargetTableName = "tbl_identification_levels", Weight = 20},
            new {  SourceTableName = "tbl_abundance_modifications", TargetTableName = "tbl_abundances", Weight = 20},
            new {  SourceTableName = "tbl_abundance_modifications", TargetTableName = "tbl_modification_types", Weight = 20},
            new {  SourceTableName = "tbl_abundances", TargetTableName = "tbl_abundance_elements", Weight = 20},
            new {  SourceTableName = "tbl_abundances", TargetTableName = "tbl_abundance_ident_levels", Weight = 20},
            new {  SourceTableName = "tbl_abundances", TargetTableName = "tbl_abundance_modifications", Weight = 20},
            new {  SourceTableName = "tbl_abundances", TargetTableName = "tbl_analysis_entities", Weight = 1},
            new {  SourceTableName = "tbl_abundances", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_activity_types", TargetTableName = "tbl_taxa_seasonality", Weight = 20},
            new {  SourceTableName = "tbl_aggregate_datasets", TargetTableName = "tbl_aggregate_order_types", Weight = 20},
            new {  SourceTableName = "tbl_aggregate_datasets", TargetTableName = "tbl_aggregate_sample_ages", Weight = 20},
            new {  SourceTableName = "tbl_aggregate_datasets", TargetTableName = "tbl_aggregate_samples", Weight = 20},
            new {  SourceTableName = "tbl_aggregate_datasets", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_aggregate_order_types", TargetTableName = "tbl_aggregate_datasets", Weight = 20},
            new {  SourceTableName = "tbl_aggregate_sample_ages", TargetTableName = "tbl_aggregate_datasets", Weight = 20},
            new {  SourceTableName = "tbl_aggregate_sample_ages", TargetTableName = "tbl_analysis_entity_ages", Weight = 20},
            new {  SourceTableName = "tbl_aggregate_samples", TargetTableName = "tbl_aggregate_datasets", Weight = 20},
            new {  SourceTableName = "tbl_aggregate_samples", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_alt_ref_types", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_alt_ref_types", TargetTableName = "tbl_sample_alt_refs", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "metainformation.view_abundance", Weight = 2},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "metainformation.view_abundances_by_taxon_analysis_entity", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_abundances", Weight = 1},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_aggregate_samples", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_analysis_entity_ages", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_analysis_entity_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_analysis_entity_prep_methods", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_ceramics", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_datasets", Weight = 1},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_dendro", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_dendro_dates", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_geochronology", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_measured_values", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_physical_samples", Weight = 1},
            new {  SourceTableName = "tbl_analysis_entities", TargetTableName = "tbl_tephra_dates", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entity_ages", TargetTableName = "tbl_aggregate_sample_ages", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entity_ages", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entity_ages", TargetTableName = "tbl_chronologies", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entity_dimensions", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entity_dimensions", TargetTableName = "tbl_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entity_prep_methods", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_analysis_entity_prep_methods", TargetTableName = "tbl_methods", Weight = 20},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "metainformation.view_sample_group_references", Weight = 80},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "metainformation.view_site_references", Weight = 80},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "metainformation.view_taxa_biblio", Weight = 10},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_aggregate_datasets", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_biblio_keywords", Weight = 20},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_dataset_masters", Weight = 200},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_datasets", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_ecocode_systems", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_geochron_refs", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_methods", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_rdb_systems", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_relative_age_refs", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_sample_group_references", Weight = 90},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_site_other_records", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_site_references", Weight = 90},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_species_associations", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_taxa_synonyms", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_taxonomic_order_biblio", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_taxonomy_notes", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_tephra_refs", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_text_biology", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_text_distribution", Weight = 150},
            new {  SourceTableName = "tbl_biblio", TargetTableName = "tbl_text_identification_keys", Weight = 150},
            new {  SourceTableName = "tbl_biblio_keywords", TargetTableName = "tbl_biblio", Weight = 20},
            new {  SourceTableName = "tbl_biblio_keywords", TargetTableName = "tbl_keywords", Weight = 20},
            new {  SourceTableName = "tbl_ceramics", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_ceramics", TargetTableName = "tbl_ceramics_measurements", Weight = 20},
            new {  SourceTableName = "tbl_ceramics_measurement_lookup", TargetTableName = "tbl_ceramics_measurements", Weight = 20},
            new {  SourceTableName = "tbl_ceramics_measurements", TargetTableName = "tbl_ceramics", Weight = 20},
            new {  SourceTableName = "tbl_ceramics_measurements", TargetTableName = "tbl_ceramics_measurement_lookup", Weight = 20},
            new {  SourceTableName = "tbl_ceramics_measurements", TargetTableName = "tbl_methods", Weight = 20},
            new {  SourceTableName = "tbl_chron_control_types", TargetTableName = "tbl_chron_controls", Weight = 20},
            new {  SourceTableName = "tbl_chron_controls", TargetTableName = "tbl_chron_control_types", Weight = 20},
            new {  SourceTableName = "tbl_chron_controls", TargetTableName = "tbl_chronologies", Weight = 20},
            new {  SourceTableName = "tbl_chronologies", TargetTableName = "tbl_analysis_entity_ages", Weight = 20},
            new {  SourceTableName = "tbl_chronologies", TargetTableName = "tbl_chron_controls", Weight = 20},
            new {  SourceTableName = "tbl_chronologies", TargetTableName = "tbl_contacts", Weight = 20},
            new {  SourceTableName = "tbl_chronologies", TargetTableName = "tbl_sample_groups", Weight = 20},
            new {  SourceTableName = "tbl_collections_or_journals", TargetTableName = "tbl_publishers", Weight = 20},
            new {  SourceTableName = "tbl_colours", TargetTableName = "tbl_methods", Weight = 20},
            new {  SourceTableName = "tbl_colours", TargetTableName = "tbl_sample_colours", Weight = 20},
            new {  SourceTableName = "tbl_contact_types", TargetTableName = "tbl_dataset_contacts", Weight = 20},
            new {  SourceTableName = "tbl_contacts", TargetTableName = "tbl_chronologies", Weight = 20},
            new {  SourceTableName = "tbl_contacts", TargetTableName = "tbl_dataset_contacts", Weight = 20},
            new {  SourceTableName = "tbl_contacts", TargetTableName = "tbl_dataset_masters", Weight = 20},
            new {  SourceTableName = "tbl_contacts", TargetTableName = "tbl_dataset_submissions", Weight = 20},
            new {  SourceTableName = "tbl_contacts", TargetTableName = "tbl_dating_labs", Weight = 20},
            new {  SourceTableName = "tbl_contacts", TargetTableName = "tbl_site_images", Weight = 20},
            new {  SourceTableName = "tbl_contacts", TargetTableName = "tbl_taxa_reference_specimens", Weight = 20},
            new {  SourceTableName = "tbl_coordinate_method_dimensions", TargetTableName = "tbl_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_coordinate_method_dimensions", TargetTableName = "tbl_methods", Weight = 20},
            new {  SourceTableName = "tbl_coordinate_method_dimensions", TargetTableName = "tbl_sample_coordinates", Weight = 20},
            new {  SourceTableName = "tbl_coordinate_method_dimensions", TargetTableName = "tbl_sample_group_coordinates", Weight = 20},
            new {  SourceTableName = "tbl_data_type_groups", TargetTableName = "tbl_data_types", Weight = 20},
            new {  SourceTableName = "tbl_data_types", TargetTableName = "tbl_data_type_groups", Weight = 20},
            new {  SourceTableName = "tbl_data_types", TargetTableName = "tbl_datasets", Weight = 20},
            new {  SourceTableName = "tbl_dataset_contacts", TargetTableName = "tbl_contact_types", Weight = 20},
            new {  SourceTableName = "tbl_dataset_contacts", TargetTableName = "tbl_contacts", Weight = 20},
            new {  SourceTableName = "tbl_dataset_contacts", TargetTableName = "tbl_datasets", Weight = 20},
            new {  SourceTableName = "tbl_dataset_masters", TargetTableName = "tbl_biblio", Weight = 200},
            new {  SourceTableName = "tbl_dataset_masters", TargetTableName = "tbl_contacts", Weight = 20},
            new {  SourceTableName = "tbl_dataset_masters", TargetTableName = "tbl_datasets", Weight = 20},
            new {  SourceTableName = "tbl_dataset_submission_types", TargetTableName = "tbl_dataset_submissions", Weight = 20},
            new {  SourceTableName = "tbl_dataset_submissions", TargetTableName = "tbl_contacts", Weight = 20},
            new {  SourceTableName = "tbl_dataset_submissions", TargetTableName = "tbl_dataset_submission_types", Weight = 20},
            new {  SourceTableName = "tbl_dataset_submissions", TargetTableName = "tbl_datasets", Weight = 20},
            new {  SourceTableName = "tbl_datasets", TargetTableName = "tbl_analysis_entities", Weight = 1},
            new {  SourceTableName = "tbl_datasets", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_datasets", TargetTableName = "tbl_data_types", Weight = 20},
            new {  SourceTableName = "tbl_datasets", TargetTableName = "tbl_dataset_contacts", Weight = 20},
            new {  SourceTableName = "tbl_datasets", TargetTableName = "tbl_dataset_masters", Weight = 20},
            new {  SourceTableName = "tbl_datasets", TargetTableName = "tbl_dataset_submissions", Weight = 20},
            new {  SourceTableName = "tbl_datasets", TargetTableName = "tbl_datasets", Weight = 20},
            new {  SourceTableName = "tbl_datasets", TargetTableName = "tbl_methods", Weight = 1},
            new {  SourceTableName = "tbl_datasets", TargetTableName = "tbl_projects", Weight = 20},
            new {  SourceTableName = "tbl_dating_labs", TargetTableName = "tbl_contacts", Weight = 20},
            new {  SourceTableName = "tbl_dating_labs", TargetTableName = "tbl_geochronology", Weight = 20},
            new {  SourceTableName = "tbl_dating_material", TargetTableName = "tbl_abundance_elements", Weight = 20},
            new {  SourceTableName = "tbl_dating_material", TargetTableName = "tbl_geochronology", Weight = 20},
            new {  SourceTableName = "tbl_dating_material", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_dating_uncertainty", TargetTableName = "tbl_dendro_dates", Weight = 20},
            new {  SourceTableName = "tbl_dating_uncertainty", TargetTableName = "tbl_geochronology", Weight = 20},
            new {  SourceTableName = "tbl_dating_uncertainty", TargetTableName = "tbl_relative_dates", Weight = 20},
            new {  SourceTableName = "tbl_dating_uncertainty", TargetTableName = "tbl_tephra_dates", Weight = 20},
            new {  SourceTableName = "tbl_dendro", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_dendro", TargetTableName = "tbl_dendro_measurements", Weight = 20},
            new {  SourceTableName = "tbl_dendro_date_notes", TargetTableName = "tbl_dendro_dates", Weight = 20},
            new {  SourceTableName = "tbl_dendro_dates", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_dendro_dates", TargetTableName = "tbl_dating_uncertainty", Weight = 20},
            new {  SourceTableName = "tbl_dendro_dates", TargetTableName = "tbl_dendro_date_notes", Weight = 20},
            new {  SourceTableName = "tbl_dendro_dates", TargetTableName = "tbl_years_types", Weight = 20},
            new {  SourceTableName = "tbl_dendro_measurement_lookup", TargetTableName = "tbl_dendro_measurements", Weight = 20},
            new {  SourceTableName = "tbl_dendro_measurements", TargetTableName = "tbl_dendro", Weight = 20},
            new {  SourceTableName = "tbl_dendro_measurements", TargetTableName = "tbl_dendro_measurement_lookup", Weight = 20},
            new {  SourceTableName = "tbl_dendro_measurements", TargetTableName = "tbl_methods", Weight = 20},
            new {  SourceTableName = "tbl_dimensions", TargetTableName = "tbl_analysis_entity_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_dimensions", TargetTableName = "tbl_coordinate_method_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_dimensions", TargetTableName = "tbl_measured_value_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_dimensions", TargetTableName = "tbl_method_groups", Weight = 20},
            new {  SourceTableName = "tbl_dimensions", TargetTableName = "tbl_sample_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_dimensions", TargetTableName = "tbl_sample_group_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_dimensions", TargetTableName = "tbl_units", Weight = 20},
            new {  SourceTableName = "tbl_ecocode_definitions", TargetTableName = "tbl_ecocode_groups", Weight = 20},
            new {  SourceTableName = "tbl_ecocode_definitions", TargetTableName = "tbl_ecocodes", Weight = 20},
            new {  SourceTableName = "tbl_ecocode_groups", TargetTableName = "tbl_ecocode_definitions", Weight = 20},
            new {  SourceTableName = "tbl_ecocode_groups", TargetTableName = "tbl_ecocode_systems", Weight = 20},
            new {  SourceTableName = "tbl_ecocode_systems", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_ecocode_systems", TargetTableName = "tbl_ecocode_groups", Weight = 20},
            new {  SourceTableName = "tbl_ecocodes", TargetTableName = "tbl_ecocode_definitions", Weight = 20},
            new {  SourceTableName = "tbl_ecocodes", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_feature_types", TargetTableName = "tbl_features", Weight = 20},
            new {  SourceTableName = "tbl_features", TargetTableName = "tbl_feature_types", Weight = 20},
            new {  SourceTableName = "tbl_features", TargetTableName = "tbl_physical_sample_features", Weight = 20},
            new {  SourceTableName = "tbl_geochron_refs", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_geochron_refs", TargetTableName = "tbl_geochronology", Weight = 20},
            new {  SourceTableName = "tbl_geochronology", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_geochronology", TargetTableName = "tbl_dating_labs", Weight = 20},
            new {  SourceTableName = "tbl_geochronology", TargetTableName = "tbl_dating_material", Weight = 20},
            new {  SourceTableName = "tbl_geochronology", TargetTableName = "tbl_dating_uncertainty", Weight = 20},
            new {  SourceTableName = "tbl_geochronology", TargetTableName = "tbl_geochron_refs", Weight = 20},
            new {  SourceTableName = "tbl_horizons", TargetTableName = "tbl_methods", Weight = 70},
            new {  SourceTableName = "tbl_horizons", TargetTableName = "tbl_sample_horizons", Weight = 20},
            new {  SourceTableName = "tbl_identification_levels", TargetTableName = "tbl_abundance_ident_levels", Weight = 20},
            new {  SourceTableName = "tbl_image_types", TargetTableName = "tbl_sample_group_images", Weight = 20},
            new {  SourceTableName = "tbl_image_types", TargetTableName = "tbl_sample_images", Weight = 20},
            new {  SourceTableName = "tbl_image_types", TargetTableName = "tbl_site_images", Weight = 20},
            new {  SourceTableName = "tbl_image_types", TargetTableName = "tbl_taxa_images", Weight = 20},
            new {  SourceTableName = "tbl_imported_taxa_replacements", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_keywords", TargetTableName = "tbl_biblio_keywords", Weight = 20},
            new {  SourceTableName = "tbl_languages", TargetTableName = "tbl_taxa_common_names", Weight = 20},
            new {  SourceTableName = "tbl_lithology", TargetTableName = "tbl_sample_groups", Weight = 20},
            new {  SourceTableName = "tbl_location_types", TargetTableName = "countries", Weight = 20},
            new {  SourceTableName = "tbl_location_types", TargetTableName = "tbl_locations", Weight = 20},
            new {  SourceTableName = "tbl_locations", TargetTableName = "tbl_location_types", Weight = 20},
            new {  SourceTableName = "tbl_locations", TargetTableName = "tbl_rdb", Weight = 150},
            new {  SourceTableName = "tbl_locations", TargetTableName = "tbl_rdb_systems", Weight = 150},
            new {  SourceTableName = "tbl_locations", TargetTableName = "tbl_relative_ages", Weight = 70},
            new {  SourceTableName = "tbl_locations", TargetTableName = "tbl_site_locations", Weight = 5},
            new {  SourceTableName = "tbl_locations", TargetTableName = "tbl_taxa_seasonality", Weight = 60},
            new {  SourceTableName = "tbl_locations", TargetTableName = "view_places_relations", Weight = 1},
            new {  SourceTableName = "tbl_mcr_names", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_mcr_summary_data", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_mcrdata_birmbeetledat", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_measured_value_dimensions", TargetTableName = "tbl_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_measured_value_dimensions", TargetTableName = "tbl_measured_values", Weight = 20},
            new {  SourceTableName = "tbl_measured_values", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_measured_values", TargetTableName = "tbl_measured_value_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_method_groups", TargetTableName = "tbl_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_method_groups", TargetTableName = "tbl_methods", Weight = 20},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_analysis_entity_prep_methods", Weight = 20},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_ceramics_measurements", Weight = 20},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_colours", Weight = 20},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_coordinate_method_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_datasets", Weight = 1},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_dendro_measurements", Weight = 20},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_horizons", Weight = 70},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_method_groups", Weight = 20},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_record_types", Weight = 20},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_relative_dates", Weight = 70},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_sample_dimensions", Weight = 150},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_sample_groups", Weight = 150},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_site_natgridrefs", Weight = 20},
            new {  SourceTableName = "tbl_methods", TargetTableName = "tbl_units", Weight = 150},
            new {  SourceTableName = "tbl_modification_types", TargetTableName = "tbl_abundance_modifications", Weight = 20},
            new {  SourceTableName = "tbl_physical_sample_features", TargetTableName = "tbl_features", Weight = 20},
            new {  SourceTableName = "tbl_physical_sample_features", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "metainformation.tbl_denormalized_measured_values", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_alt_ref_types", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_analysis_entities", Weight = 1},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_physical_sample_features", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_relative_dates", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_alt_refs", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_colours", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_coordinates", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_descriptions", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_groups", Weight = 1},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_horizons", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_images", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_locations", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_notes", Weight = 20},
            new {  SourceTableName = "tbl_physical_samples", TargetTableName = "tbl_sample_types", Weight = 20},
            new {  SourceTableName = "tbl_project_stages", TargetTableName = "tbl_projects", Weight = 20},
            new {  SourceTableName = "tbl_project_types", TargetTableName = "tbl_projects", Weight = 20},
            new {  SourceTableName = "tbl_projects", TargetTableName = "tbl_datasets", Weight = 20},
            new {  SourceTableName = "tbl_projects", TargetTableName = "tbl_project_stages", Weight = 20},
            new {  SourceTableName = "tbl_projects", TargetTableName = "tbl_project_types", Weight = 20},
            new {  SourceTableName = "tbl_publishers", TargetTableName = "tbl_collections_or_journals", Weight = 20},
            new {  SourceTableName = "tbl_rdb", TargetTableName = "countries", Weight = 150},
            new {  SourceTableName = "tbl_rdb", TargetTableName = "tbl_locations", Weight = 150},
            new {  SourceTableName = "tbl_rdb", TargetTableName = "tbl_rdb_codes", Weight = 20},
            new {  SourceTableName = "tbl_rdb", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_rdb_codes", TargetTableName = "tbl_rdb", Weight = 20},
            new {  SourceTableName = "tbl_rdb_codes", TargetTableName = "tbl_rdb_systems", Weight = 20},
            new {  SourceTableName = "tbl_rdb_systems", TargetTableName = "countries", Weight = 150},
            new {  SourceTableName = "tbl_rdb_systems", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_rdb_systems", TargetTableName = "tbl_locations", Weight = 150},
            new {  SourceTableName = "tbl_rdb_systems", TargetTableName = "tbl_rdb_codes", Weight = 20},
            new {  SourceTableName = "tbl_record_types", TargetTableName = "tbl_abundance_elements", Weight = 20},
            new {  SourceTableName = "tbl_record_types", TargetTableName = "tbl_methods", Weight = 20},
            new {  SourceTableName = "tbl_record_types", TargetTableName = "tbl_site_other_records", Weight = 150},
            new {  SourceTableName = "tbl_record_types", TargetTableName = "tbl_taxa_tree_orders", Weight = 1},
            new {  SourceTableName = "tbl_relative_age_refs", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_relative_age_refs", TargetTableName = "tbl_relative_ages", Weight = 20},
            new {  SourceTableName = "tbl_relative_age_types", TargetTableName = "tbl_relative_ages", Weight = 20},
            new {  SourceTableName = "tbl_relative_ages", TargetTableName = "countries", Weight = 70},
            new {  SourceTableName = "tbl_relative_ages", TargetTableName = "tbl_locations", Weight = 70},
            new {  SourceTableName = "tbl_relative_ages", TargetTableName = "tbl_relative_age_refs", Weight = 20},
            new {  SourceTableName = "tbl_relative_ages", TargetTableName = "tbl_relative_age_types", Weight = 20},
            new {  SourceTableName = "tbl_relative_ages", TargetTableName = "tbl_relative_dates", Weight = 20},
            new {  SourceTableName = "tbl_relative_dates", TargetTableName = "tbl_dating_uncertainty", Weight = 20},
            new {  SourceTableName = "tbl_relative_dates", TargetTableName = "tbl_methods", Weight = 70},
            new {  SourceTableName = "tbl_relative_dates", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_relative_dates", TargetTableName = "tbl_relative_ages", Weight = 20},
            new {  SourceTableName = "tbl_sample_alt_refs", TargetTableName = "tbl_alt_ref_types", Weight = 20},
            new {  SourceTableName = "tbl_sample_alt_refs", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_sample_colours", TargetTableName = "tbl_colours", Weight = 20},
            new {  SourceTableName = "tbl_sample_colours", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_sample_coordinates", TargetTableName = "tbl_coordinate_method_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_sample_coordinates", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_sample_description_sample_group_contexts", TargetTableName = "tbl_sample_description_types", Weight = 20},
            new {  SourceTableName = "tbl_sample_description_sample_group_contexts", TargetTableName = "tbl_sample_group_sampling_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_description_types", TargetTableName = "tbl_sample_description_sample_group_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_description_types", TargetTableName = "tbl_sample_descriptions", Weight = 20},
            new {  SourceTableName = "tbl_sample_descriptions", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_sample_descriptions", TargetTableName = "tbl_sample_description_types", Weight = 20},
            new {  SourceTableName = "tbl_sample_dimensions", TargetTableName = "tbl_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_sample_dimensions", TargetTableName = "tbl_methods", Weight = 150},
            new {  SourceTableName = "tbl_sample_dimensions", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_coordinates", TargetTableName = "tbl_coordinate_method_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_coordinates", TargetTableName = "tbl_sample_groups", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_description_type_sampling_contexts", TargetTableName = "tbl_sample_group_description_types", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_description_type_sampling_contexts", TargetTableName = "tbl_sample_group_sampling_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_description_types", TargetTableName = "tbl_sample_group_description_type_sampling_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_description_types", TargetTableName = "tbl_sample_group_descriptions", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_descriptions", TargetTableName = "tbl_sample_group_description_types", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_descriptions", TargetTableName = "tbl_sample_groups", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_dimensions", TargetTableName = "tbl_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_dimensions", TargetTableName = "tbl_sample_groups", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_images", TargetTableName = "tbl_image_types", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_images", TargetTableName = "tbl_sample_groups", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_notes", TargetTableName = "tbl_sample_groups", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_references", TargetTableName = "tbl_biblio", Weight = 90},
            new {  SourceTableName = "tbl_sample_group_references", TargetTableName = "tbl_sample_groups", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_sampling_contexts", TargetTableName = "tbl_sample_description_sample_group_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_sampling_contexts", TargetTableName = "tbl_sample_group_description_type_sampling_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_sampling_contexts", TargetTableName = "tbl_sample_groups", Weight = 20},
            new {  SourceTableName = "tbl_sample_group_sampling_contexts", TargetTableName = "tbl_sample_location_type_sampling_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "metainformation.view_sample_group_references", Weight = 15},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_chronologies", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_lithology", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_methods", Weight = 150},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_physical_samples", Weight = 1},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_sample_group_coordinates", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_sample_group_descriptions", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_sample_group_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_sample_group_images", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_sample_group_notes", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_sample_group_references", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_sample_group_sampling_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_groups", TargetTableName = "tbl_sites", Weight = 1},
            new {  SourceTableName = "tbl_sample_horizons", TargetTableName = "tbl_horizons", Weight = 20},
            new {  SourceTableName = "tbl_sample_horizons", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_sample_images", TargetTableName = "tbl_image_types", Weight = 20},
            new {  SourceTableName = "tbl_sample_images", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_sample_location_type_sampling_contexts", TargetTableName = "tbl_sample_group_sampling_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_location_type_sampling_contexts", TargetTableName = "tbl_sample_location_types", Weight = 20},
            new {  SourceTableName = "tbl_sample_location_types", TargetTableName = "tbl_sample_location_type_sampling_contexts", Weight = 20},
            new {  SourceTableName = "tbl_sample_location_types", TargetTableName = "tbl_sample_locations", Weight = 20},
            new {  SourceTableName = "tbl_sample_locations", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_sample_locations", TargetTableName = "tbl_sample_location_types", Weight = 20},
            new {  SourceTableName = "tbl_sample_notes", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_sample_types", TargetTableName = "tbl_physical_samples", Weight = 20},
            new {  SourceTableName = "tbl_season_types", TargetTableName = "tbl_seasons", Weight = 20},
            new {  SourceTableName = "tbl_seasons", TargetTableName = "tbl_season_types", Weight = 20},
            new {  SourceTableName = "tbl_seasons", TargetTableName = "tbl_taxa_seasonality", Weight = 20},
            new {  SourceTableName = "tbl_site_images", TargetTableName = "tbl_contacts", Weight = 20},
            new {  SourceTableName = "tbl_site_images", TargetTableName = "tbl_image_types", Weight = 20},
            new {  SourceTableName = "tbl_site_images", TargetTableName = "tbl_sites", Weight = 20},
            new {  SourceTableName = "tbl_site_locations", TargetTableName = "countries", Weight = 5},
            new {  SourceTableName = "tbl_site_locations", TargetTableName = "tbl_locations", Weight = 5},
            new {  SourceTableName = "tbl_site_locations", TargetTableName = "tbl_sites", Weight = 20},
            new {  SourceTableName = "tbl_site_natgridrefs", TargetTableName = "tbl_methods", Weight = 20},
            new {  SourceTableName = "tbl_site_natgridrefs", TargetTableName = "tbl_sites", Weight = 20},
            new {  SourceTableName = "tbl_site_other_records", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_site_other_records", TargetTableName = "tbl_record_types", Weight = 150},
            new {  SourceTableName = "tbl_site_other_records", TargetTableName = "tbl_sites", Weight = 150},
            new {  SourceTableName = "tbl_site_preservation_status", TargetTableName = "tbl_sites", Weight = 20},
            new {  SourceTableName = "tbl_site_references", TargetTableName = "tbl_biblio", Weight = 90},
            new {  SourceTableName = "tbl_site_references", TargetTableName = "tbl_sites", Weight = 20},
            new {  SourceTableName = "tbl_sites", TargetTableName = "metainformation.view_site_references", Weight = 15},
            new {  SourceTableName = "tbl_sites", TargetTableName = "tbl_sample_groups", Weight = 1},
            new {  SourceTableName = "tbl_sites", TargetTableName = "tbl_site_images", Weight = 20},
            new {  SourceTableName = "tbl_sites", TargetTableName = "tbl_site_locations", Weight = 20},
            new {  SourceTableName = "tbl_sites", TargetTableName = "tbl_site_natgridrefs", Weight = 20},
            new {  SourceTableName = "tbl_sites", TargetTableName = "tbl_site_other_records", Weight = 150},
            new {  SourceTableName = "tbl_sites", TargetTableName = "tbl_site_preservation_status", Weight = 20},
            new {  SourceTableName = "tbl_sites", TargetTableName = "tbl_site_references", Weight = 20},
            new {  SourceTableName = "tbl_species_association_types", TargetTableName = "tbl_species_associations", Weight = 20},
            new {  SourceTableName = "tbl_species_associations", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_species_associations", TargetTableName = "tbl_species_association_types", Weight = 20},
            new {  SourceTableName = "tbl_species_associations", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_taxa_common_names", TargetTableName = "tbl_languages", Weight = 20},
            new {  SourceTableName = "tbl_taxa_common_names", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_taxa_images", TargetTableName = "tbl_image_types", Weight = 20},
            new {  SourceTableName = "tbl_taxa_images", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_taxa_measured_attributes", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_taxa_reference_specimens", TargetTableName = "tbl_contacts", Weight = 20},
            new {  SourceTableName = "tbl_taxa_reference_specimens", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_taxa_seasonality", TargetTableName = "countries", Weight = 60},
            new {  SourceTableName = "tbl_taxa_seasonality", TargetTableName = "tbl_activity_types", Weight = 20},
            new {  SourceTableName = "tbl_taxa_seasonality", TargetTableName = "tbl_locations", Weight = 60},
            new {  SourceTableName = "tbl_taxa_seasonality", TargetTableName = "tbl_seasons", Weight = 20},
            new {  SourceTableName = "tbl_taxa_seasonality", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_taxa_synonyms", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_taxa_synonyms", TargetTableName = "tbl_taxa_tree_authors", Weight = 150},
            new {  SourceTableName = "tbl_taxa_synonyms", TargetTableName = "tbl_taxa_tree_families", Weight = 150},
            new {  SourceTableName = "tbl_taxa_synonyms", TargetTableName = "tbl_taxa_tree_genera", Weight = 150},
            new {  SourceTableName = "tbl_taxa_synonyms", TargetTableName = "tbl_taxa_tree_master", Weight = 150},
            new {  SourceTableName = "tbl_taxa_tree_authors", TargetTableName = "tbl_taxa_synonyms", Weight = 150},
            new {  SourceTableName = "tbl_taxa_tree_authors", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_families", TargetTableName = "tbl_taxa_synonyms", Weight = 150},
            new {  SourceTableName = "tbl_taxa_tree_families", TargetTableName = "tbl_taxa_tree_genera", Weight = 1},
            new {  SourceTableName = "tbl_taxa_tree_families", TargetTableName = "tbl_taxa_tree_orders", Weight = 1},
            new {  SourceTableName = "tbl_taxa_tree_genera", TargetTableName = "tbl_taxa_synonyms", Weight = 150},
            new {  SourceTableName = "tbl_taxa_tree_genera", TargetTableName = "tbl_taxa_tree_families", Weight = 1},
            new {  SourceTableName = "tbl_taxa_tree_genera", TargetTableName = "tbl_taxa_tree_master", Weight = 1},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "metainformation.view_abundance", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "metainformation.view_abundances_by_taxon_analysis_entity", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "metainformation.view_taxa_biblio", Weight = 2},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_abundances", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_dating_material", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_ecocodes", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_imported_taxa_replacements", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_mcr_names", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_mcr_summary_data", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_mcrdata_birmbeetledat", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_rdb", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_species_associations", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxa_common_names", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxa_images", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxa_measured_attributes", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxa_reference_specimens", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxa_seasonality", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxa_synonyms", Weight = 150},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxa_tree_authors", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxa_tree_genera", Weight = 1},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxonomic_order", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_taxonomy_notes", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_text_biology", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_text_distribution", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_master", TargetTableName = "tbl_text_identification_keys", Weight = 20},
            new {  SourceTableName = "tbl_taxa_tree_orders", TargetTableName = "tbl_record_types", Weight = 1},
            new {  SourceTableName = "tbl_taxa_tree_orders", TargetTableName = "tbl_taxa_tree_families", Weight = 1},
            new {  SourceTableName = "tbl_taxonomic_order", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_taxonomic_order", TargetTableName = "tbl_taxonomic_order_systems", Weight = 20},
            new {  SourceTableName = "tbl_taxonomic_order_biblio", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_taxonomic_order_biblio", TargetTableName = "tbl_taxonomic_order_systems", Weight = 20},
            new {  SourceTableName = "tbl_taxonomic_order_systems", TargetTableName = "tbl_taxonomic_order", Weight = 20},
            new {  SourceTableName = "tbl_taxonomic_order_systems", TargetTableName = "tbl_taxonomic_order_biblio", Weight = 20},
            new {  SourceTableName = "tbl_taxonomy_notes", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_taxonomy_notes", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_tephra_dates", TargetTableName = "tbl_analysis_entities", Weight = 20},
            new {  SourceTableName = "tbl_tephra_dates", TargetTableName = "tbl_dating_uncertainty", Weight = 20},
            new {  SourceTableName = "tbl_tephra_dates", TargetTableName = "tbl_tephras", Weight = 20},
            new {  SourceTableName = "tbl_tephra_refs", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_tephra_refs", TargetTableName = "tbl_tephras", Weight = 20},
            new {  SourceTableName = "tbl_tephras", TargetTableName = "tbl_tephra_dates", Weight = 20},
            new {  SourceTableName = "tbl_tephras", TargetTableName = "tbl_tephra_refs", Weight = 20},
            new {  SourceTableName = "tbl_text_biology", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_text_biology", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_text_distribution", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_text_distribution", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_text_identification_keys", TargetTableName = "tbl_biblio", Weight = 150},
            new {  SourceTableName = "tbl_text_identification_keys", TargetTableName = "tbl_taxa_tree_master", Weight = 20},
            new {  SourceTableName = "tbl_units", TargetTableName = "tbl_dimensions", Weight = 20},
            new {  SourceTableName = "tbl_units", TargetTableName = "tbl_methods", Weight = 150},
            new {  SourceTableName = "tbl_years_types", TargetTableName = "tbl_dendro_dates", Weight = 20},
            new {  SourceTableName = "view_places_relations", TargetTableName = "countries", Weight = 20},
            new {  SourceTableName = "view_places_relations", TargetTableName = "tbl_locations", Weight = 1}

        };


        [TestMethod]
        public void CanCreateExpectedFacetGraph()
        {
            var container = new TestDependencyService().Register();
            using (var scope = container.BeginLifetimeScope()) {
                var service = scope.Resolve<IFacetsGraph>();
                Assert.AreEqual(expectedEdges.Length, service.Edges.ToList().Count);
                foreach (var expected in expectedEdges)
                {
                    var edge = service.GetEdge(expected.SourceTableName, expected.TargetTableName);
                    Assert.IsNotNull(edge, "Expected but not found: " + expected.SourceTableName + " " + expected.TargetTableName);
                    Assert.AreEqual(expected.Weight, edge.Weight, "Weight mismatch: " + expected.SourceTableName + " " + expected.TargetTableName);
                }
            }
        }

        [TestMethod]
        public void AdjecentCloseNodesShouldHaveSingleEdgeInPath()
        {
            var container = new TestDependencyService().Register();
            using (var scope = container.BeginLifetimeScope())
            {
                var graph = scope.Resolve<IFacetsGraph>();

                GraphRoute route = graph.Find("tbl_locations", "tbl_site_locations");

                Assert.IsNotNull(route);
                Assert.AreEqual(1, route.Items.Count);
                Assert.AreEqual("tbl_locations", route.Items[0].SourceTableName);
                Assert.AreEqual("tbl_site_locations", route.Items[0].TargetTableName);
            }
        }

        [TestMethod]
        public void StartSameAsStopShouldBeEmpty()
        {
            var container = new TestDependencyService().Register();
            using (var scope = container.BeginLifetimeScope())
            {
                var graph = scope.Resolve<IFacetsGraph>();

                GraphRoute route = graph.Find("tbl_locations", "tbl_locations");

                Assert.IsNotNull(route);
                Assert.AreEqual(0, route.Items.Count);
            }
        }
    }
}
