<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>SeadQueryComposer</RootNamespace>
    <AssemblyName>sead.query.composer</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\netcoreapp31\sead.query.composer.xml</DocumentationFile>
    <NoWarn>1701;1702;1705;1591;CS1591;NU1603;SQL80001;RCS1036;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Autofac.Extras.AggregateService" Version="6.1.2" />
    <PackageReference Include="ObjectDumper.NET" Version="4.3.2" />
    <PackageReference Include="SqlKata" Version="4.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../sead.query.core/sead.query.core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Archived\**\*.cs" />
  </ItemGroup>
  <!-- <EmbeddedResource Include="Templates\**\*.sbn">
    <LogicalName>SqlTemplates.%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
  </EmbeddedResource> -->
</Project>