-- THIS IS A TEMPORARY SCRIPT  GENERATED BY create-sample SCRIPT
create schema dump_sample;
\copy sample.physical_samples_fixture from stdin with (format csv, header true);
physical_sample_id
63406
59657
20875
52534
47966
53278
6906
52422
21492
63695
63127
57594
47695
23222
62161
50816
51224
54589
55644
59091
50043
55046
47002
9027
63816
50570
59358
56040
54584
49502
54773
53205
46306
47585
55791
54082
57193
53922
48819
49335
8545
18636
52177
53455
57437
24919
1031
54933
53921
63815
48728
46243
24462
50962
56071
4781
24010
54208
46085
51603
60808
16047
53928
54132
61569
48887
51136
12343
5798
22721
59137
62017
5037
1956
62511
47425
55909
50284
46999
22376
21254
63818
47650
48983
57435
53268
60437
57666
50970
46353
20649
62459
52495
56030
62755
979
49316
48362
25117
50741
53249
62215
25801
7767
53560
53787
53737
63817
51061
52075
52868
7199
55315
20858
56588
6989
10348
1961
50621
59143
58744
48324
54663
55627
63819
898
\.

create table dump_sample.tbl_physical_samples as select * from sample.tbl_physical_samples;
create table dump_sample.tbl_aggregate_datasets as select * from sample.tbl_aggregate_datasets;
create table dump_sample.tbl_aggregate_order_types as select * from sample.tbl_aggregate_order_types;
create table dump_sample.tbl_aggregate_sample_ages as select * from sample.tbl_aggregate_sample_ages;
create table dump_sample.tbl_aggregate_samples as select * from sample.tbl_aggregate_samples;
create table dump_sample.tbl_ceramics_measurements as select * from sample.tbl_ceramics_measurements;
create table dump_sample.tbl_chronologies as select * from sample.tbl_chronologies;
create table dump_sample.tbl_colours as select * from sample.tbl_colours;
create table dump_sample.tbl_dataset_methods as select * from sample.tbl_dataset_methods;
create table dump_sample.tbl_ecocode_definitions as select * from sample.tbl_ecocode_definitions;
create table dump_sample.tbl_ecocode_groups as select * from sample.tbl_ecocode_groups;
create table dump_sample.tbl_ecocode_systems as select * from sample.tbl_ecocode_systems;
create table dump_sample.tbl_ecocodes as select * from sample.tbl_ecocodes;
create table dump_sample.tbl_geochron_refs as select * from sample.tbl_geochron_refs;
create table dump_sample.tbl_imported_taxa_replacements as select * from sample.tbl_imported_taxa_replacements;
create table dump_sample.tbl_isotope_measurements as select * from sample.tbl_isotope_measurements;
create table dump_sample.tbl_isotope_standards as select * from sample.tbl_isotope_standards;
create table dump_sample.tbl_isotope_types as select * from sample.tbl_isotope_types;
create table dump_sample.tbl_isotope_value_specifiers as select * from sample.tbl_isotope_value_specifiers;
create table dump_sample.tbl_isotopes as select * from sample.tbl_isotopes;
create table dump_sample.tbl_lithology as select * from sample.tbl_lithology;
create table dump_sample.tbl_mcr_names as select * from sample.tbl_mcr_names;
create table dump_sample.tbl_mcr_summary_data as select * from sample.tbl_mcr_summary_data;
create table dump_sample.tbl_mcrdata_birmbeetledat as select * from sample.tbl_mcrdata_birmbeetledat;
create table dump_sample.tbl_measured_value_dimensions as select * from sample.tbl_measured_value_dimensions;
create table dump_sample.tbl_sample_colours as select * from sample.tbl_sample_colours;
create table dump_sample.tbl_sample_group_images as select * from sample.tbl_sample_group_images;
create table dump_sample.tbl_sample_images as select * from sample.tbl_sample_images;
create table dump_sample.tbl_site_images as select * from sample.tbl_site_images;
create table dump_sample.tbl_site_natgridrefs as select * from sample.tbl_site_natgridrefs;
create table dump_sample.tbl_site_preservation_status as select * from sample.tbl_site_preservation_status;
create table dump_sample.tbl_taxa_images as select * from sample.tbl_taxa_images;
create table dump_sample.tbl_taxa_reference_specimens as select * from sample.tbl_taxa_reference_specimens;
create table dump_sample.tbl_taxa_synonyms as select * from sample.tbl_taxa_synonyms;
create table dump_sample.tbl_taxonomic_order_biblio as select * from sample.tbl_taxonomic_order_biblio;
create table dump_sample.tbl_temperatures as select * from sample.tbl_temperatures;
create table dump_sample.tbl_tephra_dates as select * from sample.tbl_tephra_dates;
create table dump_sample.tbl_tephra_refs as select * from sample.tbl_tephra_refs;
create table dump_sample.tbl_tephras as select * from sample.tbl_tephras;
create table dump_sample.tbl_updates_log as select * from sample.tbl_updates_log;
create table dump_sample.tbl_languages as select * from sample.tbl_languages;
create table dump_sample.tbl_abundance_elements as select * from sample.tbl_abundance_elements;
create table dump_sample.tbl_activity_types as select * from sample.tbl_activity_types;
create table dump_sample.tbl_age_types as select * from sample.tbl_age_types;
create table dump_sample.tbl_alt_ref_types as select * from sample.tbl_alt_ref_types;
create table dump_sample.tbl_ceramics_lookup as select * from sample.tbl_ceramics_lookup;
create table dump_sample.tbl_contact_types as select * from sample.tbl_contact_types;
create table dump_sample.tbl_coordinate_method_dimensions as select * from sample.tbl_coordinate_method_dimensions;
create table dump_sample.tbl_data_type_groups as select * from sample.tbl_data_type_groups;
create table dump_sample.tbl_data_types as select * from sample.tbl_data_types;
create table dump_sample.tbl_dataset_masters as select * from sample.tbl_dataset_masters;
create table dump_sample.tbl_dataset_submission_types as select * from sample.tbl_dataset_submission_types;
create table dump_sample.tbl_dating_labs as select * from sample.tbl_dating_labs;
create table dump_sample.tbl_dating_material as select * from sample.tbl_dating_material;
create table dump_sample.tbl_dating_uncertainty as select * from sample.tbl_dating_uncertainty;
create table dump_sample.tbl_dendro_lookup as select * from sample.tbl_dendro_lookup;
create table dump_sample.tbl_dimensions as select * from sample.tbl_dimensions;
create table dump_sample.tbl_feature_types as select * from sample.tbl_feature_types;
create table dump_sample.tbl_identification_levels as select * from sample.tbl_identification_levels;
create table dump_sample.tbl_image_types as select * from sample.tbl_image_types;
create table dump_sample.tbl_location_types as select * from sample.tbl_location_types;
create table dump_sample.tbl_method_groups as select * from sample.tbl_method_groups;
create table dump_sample.tbl_methods as select * from sample.tbl_methods;
create table dump_sample.tbl_modification_types as select * from sample.tbl_modification_types;
create table dump_sample.tbl_project_stages as select * from sample.tbl_project_stages;
create table dump_sample.tbl_project_types as select * from sample.tbl_project_types;
create table dump_sample.tbl_rdb_codes as select * from sample.tbl_rdb_codes;
create table dump_sample.tbl_rdb_systems as select * from sample.tbl_rdb_systems;
create table dump_sample.tbl_record_types as select * from sample.tbl_record_types;
create table dump_sample.tbl_relative_age_types as select * from sample.tbl_relative_age_types;
create table dump_sample.tbl_relative_ages as select * from sample.tbl_relative_ages;
create table dump_sample.tbl_sample_description_sample_group_contexts as select * from sample.tbl_sample_description_sample_group_contexts;
create table dump_sample.tbl_sample_description_types as select * from sample.tbl_sample_description_types;
create table dump_sample.tbl_sample_group_description_type_sampling_contexts as select * from sample.tbl_sample_group_description_type_sampling_contexts;
create table dump_sample.tbl_sample_group_description_types as select * from sample.tbl_sample_group_description_types;
create table dump_sample.tbl_sample_group_sampling_contexts as select * from sample.tbl_sample_group_sampling_contexts;
create table dump_sample.tbl_sample_location_type_sampling_contexts as select * from sample.tbl_sample_location_type_sampling_contexts;
create table dump_sample.tbl_sample_location_types as select * from sample.tbl_sample_location_types;
create table dump_sample.tbl_sample_types as select * from sample.tbl_sample_types;
create table dump_sample.tbl_season_types as select * from sample.tbl_season_types;
create table dump_sample.tbl_seasons as select * from sample.tbl_seasons;
create table dump_sample.tbl_species_association_types as select * from sample.tbl_species_association_types;
create table dump_sample.tbl_taxa_tree_orders as select * from sample.tbl_taxa_tree_orders;
create table dump_sample.tbl_taxonomic_order_systems as select * from sample.tbl_taxonomic_order_systems;
create table dump_sample.tbl_units as select * from sample.tbl_units;
create table dump_sample.tbl_value_classes as select * from sample.tbl_value_classes;
create table dump_sample.tbl_value_qualifier_symbols as select * from sample.tbl_value_qualifier_symbols;
create table dump_sample.tbl_value_qualifiers as select * from sample.tbl_value_qualifiers;
create table dump_sample.tbl_value_type_items as select * from sample.tbl_value_type_items;
create table dump_sample.tbl_value_types as select * from sample.tbl_value_types;
create table dump_sample.tbl_years_types as select * from sample.tbl_years_types;
create table dump_sample.tbl_analysis_entities as select * from sample.tbl_analysis_entities;
create table dump_sample.tbl_sample_groups as select * from sample.tbl_sample_groups;
create table dump_sample.tbl_datasets as select * from sample.tbl_datasets;
create table dump_sample.tbl_sites as select * from sample.tbl_sites;
create table dump_sample.tbl_abundances as select * from sample.tbl_abundances;
create table dump_sample.tbl_ceramics as select * from sample.tbl_ceramics;
create table dump_sample.tbl_analysis_values as select * from sample.tbl_analysis_values;
create table dump_sample.tbl_analysis_boolean_values as select * from sample.tbl_analysis_boolean_values;
create table dump_sample.tbl_analysis_categorical_values as select * from sample.tbl_analysis_categorical_values;
create table dump_sample.tbl_analysis_dating_ranges as select * from sample.tbl_analysis_dating_ranges;
create table dump_sample.tbl_analysis_entity_ages as select * from sample.tbl_analysis_entity_ages;
create table dump_sample.tbl_analysis_entity_dimensions as select * from sample.tbl_analysis_entity_dimensions;
create table dump_sample.tbl_analysis_entity_prep_methods as select * from sample.tbl_analysis_entity_prep_methods;
create table dump_sample.tbl_analysis_identifiers as select * from sample.tbl_analysis_identifiers;
create table dump_sample.tbl_analysis_integer_ranges as select * from sample.tbl_analysis_integer_ranges;
create table dump_sample.tbl_analysis_integer_values as select * from sample.tbl_analysis_integer_values;
create table dump_sample.tbl_analysis_notes as select * from sample.tbl_analysis_notes;
create table dump_sample.tbl_analysis_numerical_ranges as select * from sample.tbl_analysis_numerical_ranges;
create table dump_sample.tbl_analysis_numerical_values as select * from sample.tbl_analysis_numerical_values;
create table dump_sample.tbl_analysis_taxon_counts as select * from sample.tbl_analysis_taxon_counts;
create table dump_sample.tbl_analysis_value_dimensions as select * from sample.tbl_analysis_value_dimensions;
create table dump_sample.tbl_dendro as select * from sample.tbl_dendro;
create table dump_sample.tbl_dendro_dates as select * from sample.tbl_dendro_dates;
create table dump_sample.tbl_geochronology as select * from sample.tbl_geochronology;
create table dump_sample.tbl_measured_values as select * from sample.tbl_measured_values;
create table dump_sample.tbl_relative_dates as select * from sample.tbl_relative_dates;
create table dump_sample.tbl_sample_group_coordinates as select * from sample.tbl_sample_group_coordinates;
create table dump_sample.tbl_sample_group_descriptions as select * from sample.tbl_sample_group_descriptions;
create table dump_sample.tbl_sample_group_dimensions as select * from sample.tbl_sample_group_dimensions;
create table dump_sample.tbl_sample_group_notes as select * from sample.tbl_sample_group_notes;
create table dump_sample.tbl_sample_group_references as select * from sample.tbl_sample_group_references;
create table dump_sample.tbl_sample_horizons as select * from sample.tbl_sample_horizons;
create table dump_sample.tbl_sample_locations as select * from sample.tbl_sample_locations;
create table dump_sample.tbl_sample_alt_refs as select * from sample.tbl_sample_alt_refs;
create table dump_sample.tbl_sample_coordinates as select * from sample.tbl_sample_coordinates;
create table dump_sample.tbl_sample_descriptions as select * from sample.tbl_sample_descriptions;
create table dump_sample.tbl_sample_dimensions as select * from sample.tbl_sample_dimensions;
create table dump_sample.tbl_sample_notes as select * from sample.tbl_sample_notes;
create table dump_sample.tbl_physical_sample_features as select * from sample.tbl_physical_sample_features;
create table dump_sample.tbl_features as select * from sample.tbl_features;
create table dump_sample.tbl_site_locations as select * from sample.tbl_site_locations;
create table dump_sample.tbl_site_references as select * from sample.tbl_site_references;
create table dump_sample.tbl_projects as select * from sample.tbl_projects;
create table dump_sample.tbl_dataset_contacts as select * from sample.tbl_dataset_contacts;
create table dump_sample.tbl_dataset_submissions as select * from sample.tbl_dataset_submissions;
create table dump_sample.tbl_contacts as select * from sample.tbl_contacts;
create table dump_sample.tbl_locations as select * from sample.tbl_locations;
create table dump_sample.tbl_rdb as select * from sample.tbl_rdb;
create table dump_sample.tbl_taxa_tree_master as select * from sample.tbl_taxa_tree_master;
create table dump_sample.tbl_taxa_seasonality as select * from sample.tbl_taxa_seasonality;
create table dump_sample.tbl_species_associations as select * from sample.tbl_species_associations;
create table dump_sample.tbl_relative_age_refs as select * from sample.tbl_relative_age_refs;
create table dump_sample.tbl_taxa_common_names as select * from sample.tbl_taxa_common_names;
create table dump_sample.tbl_taxa_measured_attributes as select * from sample.tbl_taxa_measured_attributes;
create table dump_sample.tbl_taxonomic_order as select * from sample.tbl_taxonomic_order;
create table dump_sample.tbl_taxa_tree_genera as select * from sample.tbl_taxa_tree_genera;
create table dump_sample.tbl_taxa_tree_families as select * from sample.tbl_taxa_tree_families;
create table dump_sample.tbl_taxa_tree_authors as select * from sample.tbl_taxa_tree_authors;
create table dump_sample.tbl_taxonomy_notes as select * from sample.tbl_taxonomy_notes;
create table dump_sample.tbl_text_biology as select * from sample.tbl_text_biology;
create table dump_sample.tbl_site_other_records as select * from sample.tbl_site_other_records;
create table dump_sample.tbl_text_distribution as select * from sample.tbl_text_distribution;
create table dump_sample.tbl_text_identification_keys as select * from sample.tbl_text_identification_keys;
create table dump_sample.tbl_abundance_ident_levels as select * from sample.tbl_abundance_ident_levels;
create table dump_sample.tbl_abundance_modifications as select * from sample.tbl_abundance_modifications;
create table dump_sample.tbl_dendro_date_notes as select * from sample.tbl_dendro_date_notes;
create table dump_sample.tbl_horizons as select * from sample.tbl_horizons;
create table dump_sample.tbl_biblio as select * from sample.tbl_biblio;
