
### Type:   discrete
### Chain:  sites
### Picks:  (none)
POST {{protocol}}://{{host}}:{{port}}/api/facets/load
content-type: application/json
mode: cors
accept: application/json

{
    "RequestId":1,
    "RequestType":"populate",
    "TargetCode":"sites",
    "FacetConfigs":[ {
        "FacetCode":"sites",
        "Position":1,
        "Picks":[],
        "TextFilter":""
    }]
}

### Type:   range
### Chain:  tbl_denormalized_measured_values_33_0
### Picks:  (none)
POST {{protocol}}://{{host}}:{{port}}/api/facets/load
content-type: application/json
mode: cors
accept: application/json

{
    "requestId":1,
    "requestType":"populate",
    "targetCode":"tbl_denormalized_measured_values_33_0",
    "triggerCode":"tbl_denormalized_measured_values_33_0",
    "facetConfigs":[ {
        "facetCode":"tbl_denormalized_measured_values_33_0",
        "position":1,
        "picks":[],
        "textFilter":""
    }
    ]
}

### Type:   range
### Chain:  tbl_denormalized_measured_values_32
### Picks: (50, 100)
POST {{protocol}}://{{host}}:{{port}}/api/facets/load
content-type: application/json
mode: cors
accept: application/json

{
    "requestId":1,
    "requestType":"populate",
    "targetCode":"tbl_denormalized_measured_values_32",
    "triggerCode":"tbl_denormalized_measured_values_32",
    "facetConfigs":[ {
        "facetCode":"tbl_denormalized_measured_values_32",
        "position":1,
        "picks":[
            { "pickType": 2, "pickValue": "50", "text": "50"},
            { "pickType": 3, "pickValue": "100", "text": "100"}
        ],
        "textFilter":""
    }
    ]
}
