name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install semantic-release and plugins
        run: |
          sudo apt-get install bumpversion
          npm install -g semantic-release@24.2.3 \
            @semantic-release/commit-analyzer@13.0.1 \
            @semantic-release/release-notes-generator@14.0.3 \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            @semantic-release/github@11.0.1 \
            @semantic-release/exec \
            conventional-changelog-conventionalcommits@8.0.0
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
